name: Publish
on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/checkout@v4

      - name: install deps
        run: deno install

      - name: Build package
        run: deno task build

      - name: Publish to pkg pr
        run: cd npm && npx pkg-pr-new publish 
